### PR TITLE
Added a new line in add.py file

### PR DESCRIPTION
**Pull request by MOULIRAJ-E**

### CODE REVIEW

**Review by NeerajMayilvakanan — CHANGES_REQUESTED** [review]
Add one more Line

**Review by NeerajMayilvakanan — APPROVED** [review]
Accepted

**Comment by MOULIRAJ-E** [comment]
Mouliraj pull request closed

**Comment by NeerajMayilvakanan** [comment]
Mouliraj Pull Request Closed- ok

**Pull request merged**
